--- name:default
# no documentation available for this property
blur: 42 
# no documentation available for this property
hMax: 107
# no documentation available for this property
hMin: 40
# no documentation available for this property
sMax: 113
# no documentation available for this property
sMin: 0
# no documentation available for this property
steps_per_frame: 0
# no documentation available for this property
target_pixel_s: 70000
# no documentation available for this property
unsetValue: 0
# no documentation available for this property
vMax: 256 
# no documentation available for this property
vMin: 134
#--- name:structure
#blur: 0
#hMax: 253
#hMin: 16 
#maxVadapt: 255 
#minVadapt: 0 
#sMax: 251
#sMin: 4
#steps_per_frame: 0 
#target_pixel_s: 100
#unsetValue: 0
#vMax: 62
#vMin: 30
--- name:structure
steps_per_frame:  0
hMin:  70 
hMax: 103
sMin: 40
sMax: 126
vMin: -1
vMax: 256
blur: 42
--- name:structure_simulation
steps_per_frame:  0
hMin:  40
hMax: 110
sMin:  40
sMax: 110
vMin:  66
vMax: 206
blur: 149
